name = "epiccraft-mc-well-known"
type = "javascript"
compatibility_date = "2021-09-19"
# *.m4rc3l.de
routes = [
    "*epiccraft-mc.de/robots.txt",
    "*epiccraft-mc.de/.well-known/*",
]

# "*marcelcoding.ml/*",
# "*marcelcoding.tk/*"

zone_id = "36c5f8d724b98c9e8e33b3ed0a235193"
account_id = "29eab29860ff590680efdf01e8c17e45"
workers_dev = false

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
