name = "admin-guide-well-known"
type = "javascript"
compatibility_date = "2021-09-19"
# *.m4rc3l.de
routes = [
    "*admin-guide.com/robots.txt",
    "*admin-guide.com/.well-known/*",
]

# "*marcelcoding.ml/*",
# "*marcelcoding.tk/*"

zone_id = "e3324be77d2436591519504218987ad1"
account_id = "29eab29860ff590680efdf01e8c17e45"
workers_dev = false

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
